name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust as necessary for your project

      - name: Run tests
        run: |
          pytest  # Adjust this command if you use a different testing framework
